name: 'housing_pipeline'
version: '1.0.0'
config-version: 2

profile: 'housing_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  housing_pipeline:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
<<<<<<< HEAD
      +materialized: table
=======
      +materialized: table
>>>>>>> 7a919e050f610faa05eb75d0c3c766a5b0c8fc41
